version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "StateMachineStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zp0ln3odm5ij"
s3_prefix = "StateMachineStack"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
